### PR TITLE
 Brazilian portuguese translation

### PR DESCRIPTION
**Pull request by rafaelkalan**

### CODE REVIEW

**Comment by rafaelkalan** [comment]
@PiotrOsiewicz Can I know the why the pl has not been approved/merged, so I can fix and send it again.

**Comment by osiewicz** [comment]
Hey, your commit has been merged - I work on local branch beforehand so that might be why you see this pull request as closed. You are still seen as a contributor by Github. Feel free to shoot away some more questions if something is not clear. Sorry for the misunderstanding. :tongue:

**Comment by rafaelkalan** [comment]
@PiotrOsiewicz No problem man, thanks for the fast feedback, I'm really happy to be able to help on your project if there any other projects need a translation or hand let me know =D

**Comment by osiewicz** [comment]
Well, I'll consider using new language strings system altogether - the one that Criterion uses is really cool. I have a small project in mind that might require translations, so if you want to stay updated you can leave a follow. Unfortunately, I have no other projects that require translating at hand (Seeing how you've already commited to Statula). Thanks for contributing. =)

**Pull request closed without merging**
